#!/usr/bin/env python3
from pathlib import Path

FILES = [
    Path('.claude/skills/c23-standards/SKILL.md'),
    Path('docs/plans/2026-03-07-sprint-1-foundation.md'),
    Path('docs/plans/2026-03-08-ioguard-rebranding-plan.md'),
    Path('docs/plans/2026-03-08-sprint-4-dtls-compression.md'),
    Path('docs/plans/2026-03-08-sprint-5-storage-security.md'),
    Path('docs/plans/2026-03-08-sprint-6-vertical-integration.md'),
    Path('src/core/conn_data.c'),
    Path('src/core/conn_data.h'),
    Path('src/core/conn_timer.c'),
    Path('src/core/conn_timer.h'),
    Path('src/core/secmod.c'),
    Path('src/core/security_hooks.c'),
    Path('src/core/security_hooks.h'),
    Path('src/core/worker.c'),
    Path('src/core/worker.h'),
    Path('src/ipc/transport.h'),
    Path('src/network/channel.h'),
    Path('src/network/compress.c'),
    Path('src/network/compress.h'),
    Path('src/network/compress_lzs.c'),
    Path('src/network/compress_lzs.h'),
    Path('src/network/dpd.c'),
    Path('src/network/dpd.h'),
    Path('src/network/dtls_headers.c'),
    Path('src/network/dtls_headers.h'),
    Path('src/security/firewall.c'),
    Path('src/security/firewall.h'),
    Path('tests/integration/test_auth_flow.c'),
    Path('tests/integration/test_auth_mfa.c'),
    Path('tests/integration/test_data_path.c'),
    Path('tests/integration/test_dtls_channel.c'),
    Path('tests/integration/test_ipc_roundtrip.c'),
    Path('tests/integration/test_vpn_flow.c'),
    Path('tests/unit/test_compress.c'),
    Path('tests/unit/test_compress_cstp.c'),
    Path('tests/unit/test_compress_lzs.c'),
    Path('tests/unit/test_conn_data.c'),
    Path('tests/unit/test_conn_timer.c'),
    Path('tests/unit/test_dpd.c'),
    Path('tests/unit/test_dtls_headers.c'),
    Path('tests/unit/test_firewall.c'),
    Path('tests/unit/test_ipc_messages.c'),
    Path('tests/unit/test_secmod.c'),
    Path('tests/unit/test_security_hooks.c'),
]

REPLACEMENTS = {
    'IOGUARD_NETWORK_DPD_H': 'IOGUARD_NETWORK_DPD_H',
    'IOGUARD_NETWORK_COMPRESS_H': 'IOGUARD_NETWORK_COMPRESS_H',
    'IOGUARD_NETWORK_COMPRESS_LZS_H': 'IOGUARD_NETWORK_COMPRESS_LZS_H',
    'IOG_IPC_MAX_MSG_SIZE': 'IOG_IPC_MAX_MSG_SIZE',
    'IOG_FW_CHAIN_NAME_MAX': 'IOG_FW_CHAIN_NAME_MAX',
    'IOG_LZS_WINDOW_SIZE': 'IOG_LZS_WINDOW_SIZE',
    'IOG_LZS_MIN_MATCH': 'IOG_LZS_MIN_MATCH',
    'IOG_LZS_MAX_MATCH': 'IOG_LZS_MAX_MATCH',
    'iog_security_build_fw_session': 'iog_security_build_fw_session',
    'iog_dtls_parse_accept_encoding': 'iog_dtls_parse_accept_encoding',
    'iog_fw_build_destroy_batch': 'iog_fw_build_destroy_batch',
    'iog_fw_build_create_batch': 'iog_fw_build_create_batch',
    'iog_fw_session_destroy': 'iog_fw_session_destroy',
    'iog_fw_session_create': 'iog_fw_session_create',
    'iog_fw_chain_name': 'iog_fw_chain_name',
    'iog_fw_session_t': 'iog_fw_session_t',
    'iog_compress_negotiate': 'iog_compress_negotiate',
    'iog_compress_type_name': 'iog_compress_type_name',
    'iog_compress_destroy': 'iog_compress_destroy',
    'iog_compress_init': 'iog_compress_init',
    'iog_decompress': 'iog_decompress',
    'iog_compress_type_t': 'iog_compress_type_t',
    'iog_compress_ctx_t': 'iog_compress_ctx_t',
    'iog_compress(': 'iog_compress(',
    'iog_lzs_decompress': 'iog_lzs_decompress',
    'iog_lzs_compress': 'iog_lzs_compress',
    'iog_lzs_reset': 'iog_lzs_reset',
    'iog_lzs_init': 'iog_lzs_init',
    'iog_lzs_ctx_t': 'iog_lzs_ctx_t',
    'iog_dpd_should_probe': 'iog_dpd_should_probe',
    'iog_dpd_on_response': 'iog_dpd_on_response',
    'iog_dpd_on_timeout': 'iog_dpd_on_timeout',
    'iog_dpd_state_name': 'iog_dpd_state_name',
    'iog_dpd_on_request': 'iog_dpd_on_request',
    'iog_dpd_reset': 'iog_dpd_reset',
    'iog_dpd_init': 'iog_dpd_init',
    'iog_dpd_state_t': 'iog_dpd_state_t',
    'iog_dpd_ctx_t': 'iog_dpd_ctx_t',
    'Format: "iog_<username>_<iphex>"': 'Format: "iog_<username>_<iphex>"',
}

for path in FILES:
    text = path.read_text()
    original = text
    for old in sorted(REPLACEMENTS, key=len, reverse=True):
        text = text.replace(old, REPLACEMENTS[old])
    if text != original:
        path.write_text(text)
